#!/bin/sh

echo "Configuring zsh shell…"
chsh -s /bin/zsh

echo "Hiding files…"
SetFile -a "V" ~/README.md ~/LICENSE ~/scripts

echo "Excluding everything from git…"
echo '*' >> ~/.git/info/exclude

echo "Installing Homebrew…"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
./scripts/homebrew

echo "Done."
