#!/bin/sh

echo "Configuring zsh shell…"
chsh -s /bin/zsh

echo "Linking Atom configuration to Dropbox…"
rm -r ~/.atom
ln -s ~/Dropbox/Apps/Atom ~/.atom

echo "Hiding files…"
SetFile -a "V" ~/README.md ~/LICENSE ~/scripts

echo "Excluding everything from git…"
echo '*' >> ~/.git/info/exclude

echo "Installing Homebrew…"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
./scripts/homebrew

echo "Configuring Apache, MySQL, and PHP…"
./scripts/amp

echo "Done."
