#!/bin/sh

echo "Configuring zsh shell…"
chsh -s /bin/zsh

echo "Linking Atom configuration to Dropbox…"
rm -r ~/.atom
ln -s ~/Dropbox/Apps/Atom ~/.atom

echo "Installing pathogen.vim…"
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

echo "Hiding files…"
SetFile -a "V" ~/README.md ~/LICENSE ~/scripts

echo "Excluding everything from git…"
echo '*' >> ~/.git/info/exclude

echo "Installing Homebrew…"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
./scripts/homebrew

echo "Installing Ruby…"
rbenv install 2.3.0
rbenv global 2.3.0
gem install bundler

echo "Configuring Apache, MySQL, and PHP…"
./scripts/amp

echo "Installing Composer…"
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

echo "Installing Node…"
git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`
nvm install node
nvm alias default node
npm install -g npm

echo "Change Terminal Theme…"
open ./theme/base16.terminal

echo "Done."
