#!/bin/sh

brew update
brew upgrade

TAPS=(
    homebrew/dupes
    homebrew/versions
    homebrew/services
)
brew tap ${TAPS[@]}

FORMULAS=(
    git
    ruby
    node
    imagemagick
    libxml2
    libxslt
)
brew install ${FORMULAS[@]}

brew cleanup
