#!/bin/sh

brew update
brew upgrade

TAPS=(
    homebrew/dupes
    homebrew/services
)
brew tap ${TAPS[@]}

FORMULAS=(
    rbenv
    ruby-build
    rbenv-gem-rehash
    git
    imagemagick
    libxml2
    libxslt
    vim
)
brew install ${FORMULAS[@]}

brew cleanup
